on:
  push:
    branches:
      - main
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Generate CSV for test template
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: csv generation
        id: hello
        uses: actions/testTemplates-automation-githubAction@v2
        with:
          github-access-token: ${{ secrets.MY_TOKEN }}
          email-recipient: ${{ secrets.EMAIL_RECIPIENT }}
          smtp-username: ${{ secrets.SMTP_USERNAME }}
          smtp-password: ${{ secrets.SMTP_PASSWORD }}
